In [2]:
%load_ext autoreload
%autoreload 2
import os
import sys
nb_dir = os.path.split(os.getcwd())[0]
if nb_dir not in sys.path:
    sys.path.append(nb_dir)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [189]:
import mne
import numpy as np

from cerebra_atlas_python.cerebra import CerebrA
from cerebra_atlas_python.utils import setup_logging, point_cloud_to_voxel, move_volume_from_ras_to_lia,move_volume_from_lia_to_ras

In [190]:
cerebra = CerebrA()

rr.shape (256, 256, 256) uint8 1 0
rr.shape (256, 256, 256) uint8 1 0
[[ 58 136 116]
 [ 58 136 119]
 [ 58 139 113]
 ...
 [199 166 119]
 [199 166 122]
 [199 166 125]]
rr argwhere.shape (43498, 3) int64 [199 223 218] 41
[[  -1.    -0.    -0.   128.5]
 [  -0.    -0.     1.  -146.5]
 [   0.    -1.     0.   109.5]
 [   0.     0.     0.     1. ]]
rr.shape (43498, 3) float64 [70.5 71.5 42.5]-113.5
Sphere                : origin at (0.0 0.0 0.0) mm
              radius  : 95.0 mm
Source location file  : dict()
Assuming input in millimeters
Assuming input in MRI coordinates

Positions (in meters) and orientations
43498 sources


In [201]:
ras_vol,ras_affine = move_volume_from_lia_to_ras(cerebra.mni_average.t1.dataobj,cerebra.mni_average.t1.affine)
pass

In [200]:
ras_affine

array([[  1. ,   0. ,   0. , 126. ],
       [  0. ,   1. ,   0. , 146.5],
       [  0. ,   0. ,   1. , 109.5],
       [  0. ,   0. ,   0. ,   1. ]])

In [214]:
cerebra.cerebra_in_head_path

'/home/carlos/Carlos/cerebra_atlas_python/cerebra_atlas_python/cerebra_data/CerebrA_in_head.mgz'

In [215]:
import nibabel as nib
img = nib.load(cerebra.cerebra_in_head_path)

In [216]:
img.affine

array([[  -1. ,    0. ,    0. ,  128.5],
       [   0. ,    0. ,    1. , -145.5],
       [   0. ,   -1. ,    0. ,  146.5],
       [   0. ,    0. ,    0. ,    1. ]])

In [209]:
import os.path as op
surface = op.join(
    cerebra.mni_average.subjects_dir, cerebra.mni_average.subject_name, "bem", "inner_skull.surf"
)
vol_src = mne.setup_volume_source_space(
                subject=cerebra.mni_average.subject_name,
                subjects_dir=cerebra.mni_average.subjects_dir,
                surface=surface,
                mindist=0,
                add_interpolator=False,  # Just for speed!
            )

Boundary surface file : /home/carlos/Carlos/cerebra_atlas_python/cerebra_atlas_python/cerebra_data/subjects/icbm152/bem/inner_skull.surf
grid                  : 5.0 mm
mindist               : 0.0 mm
MRI volume            : /home/carlos/Carlos/cerebra_atlas_python/cerebra_atlas_python/cerebra_data/subjects/icbm152/mri/T1.mgz

Reading /home/carlos/Carlos/cerebra_atlas_python/cerebra_atlas_python/cerebra_data/subjects/icbm152/mri/T1.mgz...



Loaded bounding surface from /home/carlos/Carlos/cerebra_atlas_python/cerebra_atlas_python/cerebra_data/subjects/icbm152/bem/inner_skull.surf (10242 nodes)
Surface CM = (  -0.7   -3.9   -8.5) mm
Surface fits inside a sphere with radius  101.6 mm
Surface extent:
    x =  -77.3 ...   76.3 mm
    y =  -94.7 ...   96.6 mm
    z =  -92.6 ...   74.6 mm
Grid extent:
    x =  -80.0 ...   80.0 mm
    y =  -95.0 ...  100.0 mm
    z =  -95.0 ...   75.0 mm
46200 sources before omitting any.
32310 sources after omitting infeasible sources not within 0.0 - 101.6 mm.
Source spaces are in MRI coordinates.
Checking that the sources are inside the surface (will take a few...)
Checking surface interior status for 32310 points...
    Found  8284/32310 points inside  an interior sphere of radius   62.7 mm
    Found     0/32310 points outside an exterior sphere of radius  101.6 mm
    Found 11841/24026 points outside using surface Qhull
    Found   627/12185 points outside using solid angles
    Total 1984

In [202]:
cerebra.mni_average.head_mri_t

<Transform | head->MRI (surface RAS)>
[[ 0.99998409  0.00051499 -0.00561859 -0.00032736]
 [-0.00093964  0.99711949 -0.07584107 -0.00204062]
 [ 0.00556335  0.07584514  0.99710411 -0.05805472]
 [ 0.          0.          0.          1.        ]]

In [46]:
cerebra.mni_average.t1.affine

array([[  -1. ,    0. ,    0. ,  128.5],
       [   0. ,    0. ,    1. , -145.5],
       [   0. ,   -1. ,    0. ,  146.5],
       [   0. ,    0. ,    0. ,    1. ]])

In [47]:
np.linalg.inv(cerebra.mni_average.t1.affine)

array([[ -1. ,  -0. ,  -0. , 128.5],
       [ -0. ,  -0. ,  -1. , 146.5],
       [  0. ,   1. ,   0. , 145.5],
       [  0. ,   0. ,   0. ,   1. ]])

In [76]:
np.array(cerebra.mni_average.t1.dataobj).shape

(256, 256, 256)

In [79]:
np.array(cerebra.mni_average.t1.dataobj).max()

126

In [113]:
cerebra.mni_average.t1.affine

array([[  -1. ,    0. ,    0. ,  128.5],
       [   0. ,    0. ,    1. , -145.5],
       [   0. ,   -1. ,    0. ,  146.5],
       [   0. ,    0. ,    0. ,    1. ]])

In [124]:
cerebra.mni_average.info.get_montage()

<DigMontage | 0 extras (headshape), 0 HPIs, 3 fiducials, 111 channels>

In [125]:
cerebra.mni_average.head_mri_t

<Transform | head->MRI (surface RAS)>
[[ 0.99998409  0.00051499 -0.00561859 -0.00032736]
 [-0.00093964  0.99711949 -0.07584107 -0.00204062]
 [ 0.00556335  0.07584514  0.99710411 -0.05805472]
 [ 0.          0.          0.          1.        ]]

In [128]:
rr = cerebra.inverse_center_ras(cerebra.src_space_points)
print(rr)
rr = point_cloud_to_voxel(cerebra.src_space_points)
rr = move_volume_from_ras_to_lia(rr)
rr = np.argwhere(rr != 0)  # Back to point cloud
rr = cerebra.mni_average.center_lia(rr)
rr = rr/1000

normals = np.repeat([[0, 0, 1]], len(rr), axis=0)
pos = dict(rr=rr, nn=normals)
src_space = mne.setup_volume_source_space(pos=pos)

[[-70.  -45.5  -2.5]
 [-70.  -45.5   0.5]
 [-70.  -45.5   3.5]
 ...
 [ 71.  -21.5 -11.5]
 [ 71.  -18.5 -14.5]
 [ 71.  -18.5 -11.5]]
Sphere                : origin at (0.0 0.0 0.0) mm
              radius  : 95.0 mm
Source location file  : dict()
Assuming input in millimeters
Assuming input in MRI coordinates

Positions (in meters) and orientations
43498 sources


In [136]:
rr = point_cloud_to_voxel(cerebra.src_space_points)
print(f"rr.shape {rr.shape} {rr.dtype} {rr.max()} {rr.min()}")
rr = move_volume_from_ras_to_lia(rr)

rr.shape (256, 256, 256) uint8 1 0


In [146]:
mni_average.t1.affine

array([[  -1. ,    0. ,    0. ,  128.5],
       [   0. ,    0. ,    1. , -145.5],
       [   0. ,   -1. ,    0. ,  146.5],
       [   0. ,    0. ,    0. ,    1. ]])

In [159]:
mni_average.t1.affine

array([[  -1. ,    0. ,    0. ,  128.5],
       [   0. ,    0. ,    1. , -145.5],
       [   0. ,   -1. ,    0. ,  146.5],
       [   0. ,    0. ,    0. ,    1. ]])

In [180]:
cerebra.affine

array([[  1. ,   0. ,   0. , 126. ],
       [  0. ,   1. ,   0. , 146.5],
       [  0. ,   0. ,   1. , 109.5],
       [  0. ,   0. ,   0. ,   1. ]])

In [187]:
256-146.5

109.5

In [182]:
inv_aff = np.linalg.inv(mni_average.t1.affine)
inv_aff[:,3] = -inv_aff[:,3]
inv_aff[:,3][0] *= -1
inv_aff


array([[  -1. ,   -0. ,   -0. ,  128.5],
       [  -0. ,   -0. ,   -1. , -146.5],
       [   0. ,    1. ,    0. , -145.5],
       [   0. ,    0. ,    0. ,   -1. ]])

In [219]:
256-132

124

In [226]:
256-78

178

In [237]:
cerebra = CerebrA()
mni_average = cerebra.mni_average
mne.viz.plot_alignment(bem=mni_average.bem, mri_fiducials=mni_average.fiducials, trans=mni_average.head_mri_t, show_axes=True,dig=True, info = mni_average.info, src=cerebra.src_space)

Sphere                : origin at (0.0 0.0 0.0) mm
              radius  : 95.0 mm
Source location file  : dict()
Assuming input in millimeters
Assuming input in MRI coordinates

Positions (in meters) and orientations
43498 sources
Channel types::	eeg: 111


In [17]:
src_space_volume = point_cloud_to_voxel(cerebra.src_space_points)
src_space_volume_lia = move_volume_from_ras_to_lia(src_space_volume)

In [23]:
src_space_points_lia = np.argwhere(src_space_volume_lia != 0)
cerebra.src_space_points,src_space_points_lia

(array([[ 56, 101, 107],
        [ 56, 101, 110],
        [ 56, 101, 113],
        ...,
        [197, 125,  98],
        [197, 128,  95],
        [197, 128,  98]]),
 array([[ 58, 136, 116],
        [ 58, 136, 119],
        [ 58, 139, 113],
        ...,
        [199, 166, 119],
        [199, 166, 122],
        [199, 166, 125]]))

Channel types::	eeg: 111
